### ISSUE TITLE
[Feature] 폴더 관리

### ISSUE THREAD

**Issue by alschlee** [Team-Wash/Wash-Server#25]
# 🤖 기능 개요
폴더 관리

## ✅ Todo
- [ ] 전체 폴더 조회
- [ ] 전체 폴더 배치 조정
- [ ] 폴더 이름 수정
- [ ] 폴더 삭제
- [ ] 폴더 조회 (문제 미리보기)
