### ISSUE TITLE
[Feature] 문제 추가하기

### ISSUE THREAD

**Issue by alschlee** [Team-Wash/Wash-Server#64]
# 🤖 기능 개요

## ✅ Todo
- [x] 요청에서 incorrectCount, correctCount, orderValue 지우기
- [x] 문제가 추가될때마다 user_id별로 orderValue +1로 수정
- [x] 문제 유형 삭제하기 기능 구현
