### ISSUE TITLE
[Feature] AI 대화 저장

### ISSUE THREAD

**Issue by Joonw00** [Team-Wash/Wash-Server#93]
# 🤖 기능 개요

## ✅ Todo
- [ ] DB 변경/추가
- [ ] 저장, 조회 api 구현
- [ ] api 명세 추가
